# Horizontal Pod Autoscaler for Open-WebUI
# Scales based on CPU and memory utilization
# Range: 3-10 replicas
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: open-webui-hpa
  namespace: ollama
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-webui

  # Scaling boundaries
  minReplicas: 3   # Minimum for HA
  maxReplicas: 10  # Maximum for demo (adjust based on node capacity)

  # Scaling metrics
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale up when avg CPU > 70%

    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Scale up when avg memory > 80%

  # Scaling behavior - prevent flapping
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Remove max 1 pod per minute
        - type: Percent
          value: 10
          periodSeconds: 60  # Remove max 10% of pods per minute
      selectPolicy: Min  # Use the more conservative policy

    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60  # Add max 2 pods per minute
        - type: Percent
          value: 50
          periodSeconds: 60  # Add max 50% of pods per minute
      selectPolicy: Max  # Use the more aggressive policy
