# Azure Files Standard storage for Open-WebUI data
# Cost-effective storage for UI state and user data
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-standard-webui
  labels:
    app.kubernetes.io/name: ollama-llm-demo
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS  # Standard tier for cost efficiency
  protocol: smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
  namespace: ollama
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce  # Single pod access for UI data
  storageClassName: azurefile-standard-webui
  resources:
    requests:
      storage: 5Gi  # Small volume for UI state
