# Internal ClusterIP service for Ollama
# Accessed by Open-WebUI within the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm-server
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - name: http
      protocol: TCP
      port: 11434
      targetPort: 11434
  sessionAffinity: ClientIP  # Sticky sessions for better performance
